name: Build and Deploy Jekyll site

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
        pip install notebook

    - name: Install Ruby dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build site with Jekyll
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
